server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318

# Configuración básica de almacenamiento en el filesystem local
storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces